name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Bandit Security Scan
        run: bandit -r ./ --severity-level high --confidence-level all

      - name: Run Pip Audit
        run: pip-audit

      - name: Run Safety Security Check
        run: safety check -r requirements.txt

  deploy-lambda:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t package
          cp lambda_function.py package/
          cp email.html package/
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" > .env.production
          cp .env.production package/
          cd package
          zip -r ../function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name send-email \
            --zip-file fileb://function.zip
